name: Grafix Unlimited
favicon: null
layout_spectrum: 0.6372274933382869
typography_spectrum: 0.017746399622410536
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.4498140283394605
  lightness: 0.4533020821399987
  saturation: 0.14560979674570262
  rhythmicContrast: 0.6636018534190953
purpose: []
