name: Grafix Unlimited
favicon: null
layout_spectrum: 0.48618
typography_spectrum: 0.31626
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ced2dd'
    - '#dde5ef'
    - '#01010c'
    - '#9fa4a9'
    - '#625f80'
  brandStrength: 0.25
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
