name: Grafix Unlimited
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31626
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#7766ad'
    - '#f89a1f'
    - '#282560'
    - '#9acb3d'
    - '#ffffff'
  brandStrength: 1
  lightness: 1
  saturation: 0.75
  rhythmicContrast: 0.6636018534190953
purpose: []
