name: Grafix Unlimited
favicon: null
layout_spectrum: 0.25541
typography_spectrum: 0.12793
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#bcbcbc'
    - '#8a8a8a'
    - '#040404'
    - '#5e5e5e'
  brandStrength: 0
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
