name: Grafix Unlimited
favicon: null
layout_spectrum: 0.48618
typography_spectrum: 0.31626
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#262626'
    - '#b7b7b7'
    - '#ededed'
    - '#7f7f7f'
  brandStrength: 1
  lightness: 0.5
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
